# Generated by Django 4.2.4 on 2023-08-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrashBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_tb', models.DateField()),
                ('resident_id_tb', models.IntegerField()),
                ('weather_tb', models.CharField(choices=[('Sunny', 'Sunny'), ('Rainy', 'Rainy')], max_length=200)),
                ('day_of_week_tb', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=200)),
                ('previous_requests_tb', models.IntegerField()),
                ('public_holiday_tb', models.BooleanField()),
                ('trash_pickup_request_tb', models.BooleanField()),
            ],
        ),
    ]
