# Generated by Django 4.2.4 on 2023-08-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrashBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('resident_id', models.IntegerField()),
                ('weather', models.CharField(choices=[('Sunny', 'Sunny'), ('Rainy', 'Rainy')], max_length=200)),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=200)),
                ('previous_requests', models.IntegerField()),
                ('public_holiday', models.IntegerField()),
                ('trash_pickup_request', models.IntegerField()),
            ],
        ),
    ]
