# Generated by Django 4.2.4 on 2023-08-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trashbooking',
            old_name='day_of_week_tb',
            new_name='day_of_week',
        ),
        migrations.RenameField(
            model_name='trashbooking',
            old_name='previous_requests_tb',
            new_name='previous_requests',
        ),
        migrations.RenameField(
            model_name='trashbooking',
            old_name='public_holiday_tb',
            new_name='public_holiday',
        ),
        migrations.RenameField(
            model_name='trashbooking',
            old_name='resident_id_tb',
            new_name='resident_id',
        ),
        migrations.RenameField(
            model_name='trashbooking',
            old_name='trash_pickup_request_tb',
            new_name='trash_pickup_request',
        ),
        migrations.RenameField(
            model_name='trashbooking',
            old_name='weather_tb',
            new_name='weather',
        ),
        migrations.RemoveField(
            model_name='trashbooking',
            name='date_tb',
        ),
        migrations.AddField(
            model_name='trashbooking',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
