# Generated by Django 4.2.4 on 2023-08-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0002_rename_day_of_week_tb_trashbooking_day_of_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trashbooking',
            name='public_holiday',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trashbooking',
            name='trash_pickup_request',
            field=models.IntegerField(),
        ),
    ]
