# Generated by Django 4.2.4 on 2023-08-15 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0002_messytrashbooking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessyTrashBooking',
        ),
    ]
