# Generated by Django 4.2.4 on 2023-08-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0003_delete_messytrashbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessyTrashBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('resident_id', models.IntegerField(blank=True)),
                ('temperature', models.IntegerField(blank=True)),
                ('weather', models.CharField(blank=True, choices=[('Sunny', 'Sunny'), ('Rainy', 'Rainy')], max_length=200)),
                ('day_of_week', models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=200)),
                ('previous_requests', models.IntegerField(blank=True)),
                ('public_holiday', models.IntegerField(blank=True)),
                ('trash_pickup_request', models.IntegerField(blank=True)),
            ],
        ),
    ]
